### ISSUE TITLE
Document: dev-mingle 이미지 및 로고 디자인을 위한 파일 공유

### ISSUE THREAD

**Issue by Ilpyo-Yang** [dev-mingle/dev-mingle-server#36]
## 개요
dev-mingle 이미지 및 로고 디자인을 위한 파일 공유 이슈를 만들어봤습니다.
꼭 프론트에 반영하지 않아도 되고, readme 추가를 위한 용도입니다.

### 로고 및 디자인 확인시 사용하는 툴
+ [flaticon](https://www.flaticon.com/)
+ [Doodles](https://blush.design/collections/L9oIBvB7R7IjzZWxOfIu/open-doodles)
+ [builder](https://app.itg.digital/search/elements/7?search=developer&style=&sort=new)
+ [pickceltrue](https://www.pixeltrue.com/premium/brand-character-illustration-pack)

**Comment by Ilpyo-Yang** [comment]
![Group 51 (1)](https://github.com/dev-mingle/dev-mingle-server/assets/67682215/c1f68c0c-3244-4ea3-a4e4-e0d69d052bd4)

**Comment by Ilpyo-Yang** [comment]
![Group 51 (1)](https://github.com/dev-mingle/dev-mingle-server/assets/67682215/eb3dd6ee-e90c-4d2f-aa4f-8af461ba0c9e)

**Comment by hcgo97** [comment]
> ![Group 51 (1)](https://user-images.githubusercontent.com/67682215/268399098-eb3dd6ee-e90c-4d2f-aa4f-8af461ba0c9e.png)

3번 5번 좋아요 !!!!
